### ISSUE TITLE
Link between projects?

### ISSUE THREAD

**Issue by SteveEdson** [sindresorhus/xbar#2]
I have a similar project for PHP plugins https://github.com/SteveEdson/bitbar-php, would you like to link between the two, plus any other formatters in other languages?

No problem if not!

**Comment by sindresorhus** [comment]
I'm always happy to cross-link, but I'm unsure what value it would have in this case? People looking at this is unlikely to want the PHP version and inverse.

**Comment by SteveEdson** [comment]
You might be right, but perhaps someone will stumble across the formatter in one language and think 'i wish there was something like this for `x`'?

Like I say, just an idea.

**Comment by sindresorhus** [comment]
Ok. Gonna pass. These are better linked to from the main BitBar readme.
