### ISSUE TITLE
Move to xbar Branding?

### ISSUE THREAD

**Issue by chrisspiegl** [sindresorhus/xbar#31]
I love that this exists and is updated for ESM and new node versions.

Is it up in the cards to move this package to the new xbar branding?

**Comment by sindresorhus** [comment]
Done. I tried publishing as `xbar`, which is available, but npm doesn't allow it because `x-bar` exists... So it's `@sindresorhus/xbar`.

**Comment by chrisspiegl** [comment]
Nice, that's awesome support and really quick to update. I appreciate that 🌸.
