### ISSUE TITLE
Xbar cannot run plugin script due to esm modules

### ISSUE THREAD

**Issue by viperfx** [sindresorhus/xbar#33]
Ive setup my script with the following first two lines

```
#!/usr/bin/env ~/.nvm/versions/node/v16.9.1/bin/node --input-type=module
import xbar, { separator, isDarkMode } from "@sindresorhus/xbar";

....
```

Xbar displays the following

```
/Users/viperfx/Library/Application Support/xbar/plugins/xbar.js:2
import xbar, { separator, isDarkMode } from "@sindresorhus/xbar";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

Ive followed the readme as instructed - is there something else? PS - I installed the package with npm -g

**Comment by sindresorhus** [comment]
See the updated instructions: https://github.com/sindresorhus/xbar/commit/6bd1d81015fc735ed784e58af49e3e56b14b9f7b
