### ISSUE TITLE
node_modules causes BitBar.app to fail

### ISSUE THREAD

**Issue by fregante** [sindresorhus/xbar#4]
I tried your demo and as per https://github.com/matryer/bitbar/issues/189, BitBar fails when there are unrecognized files/folders in its plugin directory.

How do you work around the issue?

I currently install the modules in a folder outside but that transforms every require into something like 

``` js
require('../node_modules/bitbar')
```

**Comment by sindresorhus** [comment]
Weird. It works fine for me with latest BitBar (1.6, also worked fine with 1.4):

```
~/Documents/BitBar plugins
❯ tree
.
├── example.js
└── node_modules
    └── bitbar
        ├── index.js
        ├── license
        ├── node_modules
        │   └── object-assign
        │       ├── index.js
        │       ├── license
        │       ├── package.json
        │       └── readme.md
        ├── package.json
        └── readme.md

4 directories, 9 files
```

**Comment by fregante** [comment]
That's... annoyingly strange. It made me lose an hour earlier and _now it works fine._ :( When you showed me now I thought it was just because `example` came before `node_modules`
